import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, CheckCircle2, Leaf, Menu, Play, ShieldCheck } from "lucide-react";
import { useState } from "react";

import { Brand, icons } from "@/components/trialshield";
import { capabilities } from "@/components/portfolio";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [{ title: "AIIA TrialShield — Ayurveda Clinical Research Command Center" }, { name: "description", content: "Monitor clinical trials, ethics readiness, participant safety, pharmacovigilance workflows and compliance risks from a unified platform." }, { property: "og:title", content: "AIIA TrialShield" }, { property: "og:description", content: "Ayurveda Clinical Research & Pharmacovigilance Command Center." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }),
  component: LandingPage,
});

function LandingPage() {
  const [menuOpen, setMenuOpen] = useState(false);
  return <div className="min-h-screen overflow-hidden bg-background text-foreground">
    <header className="absolute inset-x-0 top-0 z-40 border-b border-primary-foreground/10 text-primary-foreground"><div className="mx-auto grid h-20 max-w-[1440px] grid-cols-[minmax(0,1fr)_auto] items-center px-5 lg:grid-cols-[260px_minmax(0,1fr)_260px] lg:px-10"><div className="[&_strong]:text-primary-foreground [&_span_span]:text-primary-foreground/55"><Brand /></div><nav className="hidden justify-center gap-8 text-xs font-medium lg:flex"><a href="#capabilities" className="text-primary-foreground/70 hover:text-primary-foreground">Capabilities</a><a href="#approach" className="text-primary-foreground/70 hover:text-primary-foreground">Platform</a><a href="#standards" className="text-primary-foreground/70 hover:text-primary-foreground">Standards</a></nav><div className="flex justify-end"><Button asChild variant="accent" size="sm" className="hidden sm:inline-flex"><Link to="/platform">Enter Platform<ArrowRight className="size-4" /></Link></Button><Button variant="ghost" size="icon" className="text-primary-foreground lg:hidden" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle menu"><Menu className="size-5" /></Button></div></div>{menuOpen && <div className="border-t border-primary-foreground/10 bg-primary px-5 py-4 lg:hidden"><Button asChild variant="accent" className="w-full"><Link to="/platform">Enter Platform</Link></Button></div>}</header>
    <main>
      <section className="botanical-field manuscript-grid relative min-h-[760px] bg-primary pt-20 text-primary-foreground lg:min-h-[800px]"><div className="absolute inset-y-0 right-0 w-[42%] border-l border-primary-foreground/8 opacity-70" /><div className="absolute right-[7%] top-[17%] hidden h-[570px] w-[350px] opacity-35 lg:block"><BotanicalDrawing /></div><div className="relative mx-auto flex min-h-[680px] max-w-[1440px] items-center px-5 py-20 lg:px-10"><div className="max-w-4xl animate-fade-in"><div className="mb-8 inline-flex items-center gap-2 border-l-2 border-accent pl-3 text-[11px] font-semibold uppercase tracking-[0.18em] text-primary-foreground/65"><span className="size-1.5 rounded-full bg-accent" />AIIA research infrastructure</div><h1 className="font-display text-5xl font-semibold leading-[1.02] sm:text-7xl lg:text-[92px]">AIIA<br /><span className="text-accent">TrialShield</span></h1><p className="mt-7 max-w-2xl font-display text-xl leading-8 text-primary-foreground/92 sm:text-2xl">Ayurveda Clinical Research &<br className="hidden sm:block" /> Pharmacovigilance Command Center</p><p className="mt-6 max-w-xl text-sm leading-7 text-primary-foreground/62 sm:text-base">Monitor clinical trials, ethics readiness, participant safety, pharmacovigilance workflows and compliance risks from a unified platform.</p><div className="mt-9 flex flex-wrap gap-3"><Button asChild variant="accent" size="lg"><Link to="/platform">Explore Platform<ArrowRight className="size-4" /></Link></Button><Button asChild size="lg" className="border border-primary-foreground/20 bg-primary-foreground/5 hover:bg-primary-foreground/10"><Link to="/platform"><Play className="size-4" />View Demo</Link></Button></div></div></div><div className="absolute bottom-0 left-0 right-0 border-t border-primary-foreground/10"><div className="mx-auto grid max-w-[1440px] grid-cols-2 divide-x divide-primary-foreground/10 px-5 lg:grid-cols-4 lg:px-10">{[["12", "Active studies"], ["18", "Research sites"], ["680", "Participants planned"], ["24/7", "Safety surveillance"]].map(([value, label]) => <div key={label} className="px-4 py-5 first:pl-0 lg:py-6"><strong className="font-display text-xl">{value}</strong><span className="ml-2 text-[11px] text-primary-foreground/55">{label}</span></div>)}</div></div></section>
      <section id="approach" className="border-b border-border bg-surface py-24 lg:py-32"><div className="mx-auto grid max-w-[1280px] gap-12 px-5 lg:grid-cols-[.7fr_1.3fr] lg:px-10"><div><p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-secondary">The operational question</p><h2 className="mt-4 font-display text-3xl font-semibold leading-tight sm:text-4xl">Clarity before complexity.</h2></div><div><p className="max-w-3xl font-display text-2xl leading-9 text-foreground/85">Every screen begins with what needs attention, explains why it is at risk, identifies who owns it and makes the next action explicit.</p><div className="mt-10 grid gap-px overflow-hidden rounded-lg border border-border bg-border sm:grid-cols-3">{[["Attention", "Prioritised in context"], ["Evidence", "Traceable to source"], ["Action", "Assigned and time-bound"]].map(([title, body]) => <div key={title} className="bg-background p-6"><CheckCircle2 className="size-5 text-secondary" /><h3 className="mt-5 text-sm font-semibold">{title}</h3><p className="mt-1 text-xs text-muted-foreground">{body}</p></div>)}</div></div></div></section>
      <section id="capabilities" className="py-24 lg:py-32"><div className="mx-auto max-w-[1280px] px-5 lg:px-10"><div className="max-w-2xl"><p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-secondary">Unified research operations</p><h2 className="mt-4 font-display text-4xl font-semibold">From protocol to public safety.</h2><p className="mt-4 text-sm leading-7 text-muted-foreground">One coherent operating environment for the evidence, decisions and accountability behind Ayurveda clinical research.</p></div><div className="mt-14 grid border-l border-t border-border sm:grid-cols-2 lg:grid-cols-3">{capabilities.map(([title, description, Icon], index) => <article key={title} className="group min-h-56 border-b border-r border-border bg-surface p-7 transition-colors hover:bg-muted/40"><div className="flex items-start justify-between"><span className="grid size-9 place-items-center rounded-md bg-primary/7 text-primary"><Icon className="size-4.5" /></span><span className="text-[10px] font-semibold text-muted-foreground">0{index + 1}</span></div><h3 className="mt-7 font-display text-base font-semibold">{title}</h3><p className="mt-3 text-xs leading-5 text-muted-foreground">{description}</p></article>)}</div></div></section>
      <section id="standards" className="bg-primary py-24 text-primary-foreground"><div className="mx-auto grid max-w-[1280px] items-center gap-12 px-5 lg:grid-cols-2 lg:px-10"><div><Leaf className="size-7 text-accent" /><h2 className="mt-6 font-display text-4xl font-semibold leading-tight">Rooted in Ayurveda.<br />Built for rigorous evidence.</h2><p className="mt-5 max-w-xl text-sm leading-7 text-primary-foreground/62">Purpose-built intervention records preserve formulation, dosage, anupana and treatment context while remaining ready for FHIR and CDISC exchange.</p><Button asChild variant="accent" className="mt-8"><Link to="/platform">Enter the command center<ArrowRight className="size-4" /></Link></Button></div><div className="rounded-lg border border-primary-foreground/15 bg-primary-foreground/5 p-6"><div className="flex items-center justify-between border-b border-primary-foreground/10 pb-5"><div><p className="text-[10px] uppercase tracking-[0.14em] text-primary-foreground/50">Intervention record</p><h3 className="mt-2 font-display text-xl font-semibold">Nishamalaki Churna</h3></div><Leaf className="size-8 text-accent" /></div><dl className="mt-6 grid grid-cols-2 gap-6 text-sm"><div><dt className="text-primary-foreground/45">Dosage</dt><dd className="mt-1 font-medium">3 g, twice daily</dd></div><div><dt className="text-primary-foreground/45">Anupana</dt><dd className="mt-1 font-medium">Lukewarm water</dd></div><div><dt className="text-primary-foreground/45">Duration</dt><dd className="mt-1 font-medium">12 weeks</dd></div><div><dt className="text-primary-foreground/45">Batch traceability</dt><dd className="mt-1 font-medium">Verified</dd></div></dl></div></div></section>
    </main>
    <footer className="border-t border-border bg-surface"><div className="mx-auto flex max-w-[1280px] flex-col gap-5 px-5 py-8 sm:flex-row sm:items-center sm:justify-between lg:px-10"><Brand /><p className="text-xs text-muted-foreground">Illustrative institutional research environment · 2026</p></div></footer>
  </div>;
}

function BotanicalDrawing() { return <svg viewBox="0 0 350 570" fill="none" aria-hidden="true"><path d="M163 551C171 414 158 287 218 99" stroke="currentColor" strokeWidth="1.2"/><path d="M198 169C147 143 109 156 86 207C129 214 173 202 198 169Z" stroke="currentColor"/><path d="M178 257C226 219 267 223 299 266C254 285 211 278 178 257Z" stroke="currentColor"/><path d="M166 341C121 310 82 320 56 362C98 375 139 365 166 341Z" stroke="currentColor"/><path d="M164 429C211 392 252 398 282 442C239 459 195 452 164 429Z" stroke="currentColor"/><path d="M218 99C213 61 233 31 267 13C282 54 261 88 218 99Z" stroke="currentColor"/><path d="M102 484C126 457 146 443 164 429M104 484C74 468 54 474 43 503C70 510 91 502 104 484Z" stroke="currentColor"/></svg>; }