import { Link } from "@tanstack/react-router";
import { ArrowRight, BookOpenCheck, Check, CircleAlert, FlaskConical, Leaf, ShieldCheck, TrendingUp } from "lucide-react";
import { toast } from "sonner";

import { AttentionItem, PlatformPage, ProgressBar, StatusPill, Timeline } from "@/components/trialshield";
import { Button } from "@/components/ui/button";
import { getStudyProgress, useWorkflow } from "@/components/workflow-state";
import { buildClinicalReportRows, downloadClinicalReport } from "@/lib/clinical-report";
import { useAuth } from "@/lib/auth-context";
import { can } from "@/lib/permissions";
import { detectSafetySignals } from "@/lib/safety-signals";

export function PortfolioWorkspace() {
  const workflow = useWorkflow();
  const { profile } = useAuth();
  const reportRows = buildClinicalReportRows(workflow.studies, workflow.safetyCases, workflow.batches);
  const safetySignals = detectSafetySignals(workflow.safetyCases, workflow.batches);
  const activeStudies = workflow.studies.filter((study) => !study.archived);
  const totalEnrolled = reportRows.reduce((total, row) => total + row.enrolled, 0);
  const totalTarget = reportRows.reduce((total, row) => total + row.target, 0);
  const recruitment = totalTarget ? Math.round(totalEnrolled / totalTarget * 100) : 0;
  const openSaes = workflow.safetyCases.filter((item) => item.severity === "SAE" && item.stage !== "closed");
  const openRisks = workflow.risks.filter((risk) => !risk.resolved);
  const closedSaes = workflow.safetyCases.filter((item) => item.severity === "SAE" && item.stage === "closed").length;
  const meanCompleteness = reportRows.length ? Math.round(reportRows.reduce((total, row) => total + row.dataCompleteness, 0) / reportRows.length) : 0;
  const priorities = [
    ...openSaes.slice(0, 2).map((item) => ({ key: item.id, severity: "critical" as const, title: `${item.id} · ${item.title}`, meta: `${item.studyId} · ${item.stage.replaceAll("-", " ")} · Due ${item.due}`, owner: item.owner, action: "Advance", onAction: () => { workflow.advanceSafetyCase(item.id); toast.success(`${item.id} moved to the next review step.`); } })),
    ...openRisks.slice(0, 2).map((risk) => ({ key: risk.id, severity: risk.severity === "High" ? "critical" as const : "warning" as const, title: risk.title, meta: `${risk.studyId} · ${risk.detail}`, owner: risk.owner, action: "Resolve", onAction: () => { workflow.resolveRisk(risk.id); toast.success(`${risk.title} resolved.`); } })),
  ].slice(0, 3);
  const recentActions = workflow.auditEntries.slice(0, 3).map((entry) => ({ title: entry.action, detail: `${entry.studyId} · ${entry.actor}`, time: new Date(entry.timestamp).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }), state: "done" as const }));

  const displayName = profile?.full_name || profile?.email || "Research user";
  return <PlatformPage eyebrow={`National research portfolio · ${profile?.role ?? "Account"}`} title={`Good morning, ${displayName}`} description={`${priorities.length} matters need attention. Trial stages and KPI totals update as actions are recorded.`} actions={<Button variant="secondary" onClick={() => { if (downloadClinicalReport("pdf", reportRows)) toast.success("Print-ready weekly brief opened. Choose Save as PDF in the print dialog."); else toast.error("Allow pop-ups to open the weekly brief."); }}>Weekly brief<ArrowRight className="size-4" /></Button>}>
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1.5fr)_minmax(320px,.72fr)]">
      <div className="space-y-6">
        <section className="rounded-lg border border-border bg-surface p-5 shadow-xs sm:p-6">
          <div className="grid grid-cols-[minmax(0,1fr)_auto] items-start gap-5"><div><div className="flex items-center gap-2"><span className={`size-2 rounded-full ${priorities.length ? "bg-risk" : "bg-positive"}`} /><p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-risk">Institutional attention</p></div><h2 className="mt-2 font-display text-xl font-semibold">What needs action now</h2></div><StatusPill tone={priorities.length ? "risk" : "good"}>{priorities.length} priorities</StatusPill></div>
          <div className="mt-2">{priorities.length ? priorities.map((item) => <AttentionItem key={item.key} severity={item.severity} title={item.title} meta={item.meta} owner={item.owner} action={item.action} onAction={item.onAction} />) : <p className="py-5 text-sm text-muted-foreground">No urgent safety or compliance actions are open.</p>}</div>
        </section>
        <section className="grid gap-4 lg:grid-cols-2">
          <article className="rounded-lg border border-border bg-surface p-5"><div className="flex items-center justify-between"><div><p className="text-[11px] font-semibold uppercase tracking-[0.14em] text-secondary">Recruitment journey</p><h2 className="mt-1 font-display text-lg font-semibold">{totalEnrolled} of {totalTarget} participants</h2></div><span className="font-display text-2xl font-semibold">{recruitment}%</span></div><div className="mt-5"><ProgressBar value={recruitment} /></div><div className="mt-5 grid grid-cols-3 divide-x divide-border text-center"><div><strong className="block text-sm">{Math.max(0, totalTarget - totalEnrolled)}</strong><span className="text-[11px] text-muted-foreground">Remaining</span></div><div><strong className="block text-sm">{totalEnrolled}</strong><span className="text-[11px] text-muted-foreground">Enrolled</span></div><div><strong className="block text-sm">{activeStudies.reduce((total, study) => total + study.activatedSites, 0)}</strong><span className="text-[11px] text-muted-foreground">Active sites</span></div></div></article>
          <article className="rounded-lg border border-border bg-surface p-5"><div className="flex items-center justify-between"><div><p className="text-[11px] font-semibold uppercase tracking-[0.14em] text-secondary">Portfolio health</p><h2 className="mt-1 font-display text-lg font-semibold">{openSaes.length + openRisks.length ? "Monitoring required" : "No open exceptions"}</h2></div><div className="grid size-14 place-items-center rounded-full border-4 border-secondary/20 font-display text-lg font-semibold text-primary">{activeStudies.length}</div></div><div className="mt-5 space-y-3 text-xs"><div className="flex justify-between"><span className="text-muted-foreground">Ethics-ready studies</span><strong>{activeStudies.filter((study) => ["ctri", "sites", "recruitment", "follow-up", "close-out"].includes(study.stage)).length} / {activeStudies.length}</strong></div><div className="flex justify-between"><span className="text-muted-foreground">SAE closure</span><strong>{openSaes.length + closedSaes ? Math.round(closedSaes / (openSaes.length + closedSaes) * 100) : 100}%</strong></div><div className="flex justify-between"><span className="text-muted-foreground">Data completeness</span><strong>{meanCompleteness}%</strong></div></div></article>
        </section>
        <section className="rounded-lg border border-border bg-surface p-6"><div className="flex items-center justify-between"><div><p className="text-[11px] font-semibold uppercase tracking-[0.14em] text-secondary">Study portfolio</p><h2 className="mt-1 font-display text-xl font-semibold">Operational focus</h2></div><Button asChild variant="ghost" size="sm"><Link to="/studies">All studies<ArrowRight className="size-4" /></Link></Button></div><div className="mt-5 grid gap-4 md:grid-cols-3">{activeStudies.slice(0, 3).map((study) => { const progress = getStudyProgress(study); return <Link key={study.id} to="/studies/$studyId" params={{ studyId: study.id }} className="rounded-md border border-border p-4 transition-colors hover:border-secondary/40 hover:bg-muted/40"><div className="flex justify-between gap-2"><span className="text-[10px] font-semibold text-secondary">{study.id}</span><StatusPill tone={study.risk === "High" ? "risk" : study.risk === "Moderate" ? "warn" : "good"}>{study.risk}</StatusPill></div><h3 className="mt-3 text-sm font-semibold">{study.title}</h3><p className="mt-2 text-[11px] text-muted-foreground">{study.status}</p><div className="mt-4"><ProgressBar value={progress} tone={study.risk === "High" ? "risk" : "primary"} /></div><p className="mt-2 text-[11px] text-muted-foreground">{study.enrolled} / {study.target} enrolled</p></Link>; })}</div></section>
      </div>
      <aside className="space-y-6"><section className="rounded-lg bg-primary p-6 text-primary-foreground"><div className="flex items-start justify-between"><div><p className="text-[11px] font-semibold uppercase tracking-[0.14em] text-primary-foreground/60">Safety monitoring</p><h2 className="mt-2 font-display text-xl font-semibold">Active surveillance</h2></div><ShieldCheck className="size-6 text-accent" /></div><p className="mt-5 text-4xl font-semibold">{openSaes.length}</p><p className="mt-1 text-sm text-primary-foreground/65">open serious adverse events</p><div className="mt-6 border-t border-primary-foreground/15 pt-5"><div className="flex items-center justify-between text-sm"><span>Regulatory reporting</span><strong>{openSaes.filter((item) => item.stage === "regulatory-reporting").length}</strong></div><div className="mt-3 flex items-center justify-between text-sm"><span>Follow-ups in progress</span><strong>{openSaes.filter((item) => item.stage === "follow-up").length}</strong></div></div><Button asChild variant="accent" className="mt-6 w-full"><Link to="/safety">Open safety workspace<ArrowRight className="size-4" /></Link></Button></section>
      <section className="rounded-lg border border-border bg-surface p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-[11px] font-semibold uppercase tracking-[0.14em] text-risk">Safety surveillance</p><h2 className="mt-1 font-display text-base font-semibold">{safetySignals.length} active signal{safetySignals.length === 1 ? "" : "s"}</h2></div><StatusPill tone={safetySignals.some((signal) => signal.level === "High") ? "risk" : safetySignals.length ? "warn" : "good"}>{safetySignals.some((signal) => signal.level === "High") ? "Review now" : safetySignals.length ? "Review" : "Clear"}</StatusPill></div>{safetySignals.length ? <ul className="mt-4 space-y-3">{safetySignals.slice(0, 2).map((signal) => <li key={signal.id} className="border-t border-border pt-3"><p className="text-sm font-semibold">{signal.title}</p><p className="mt-1 text-xs text-muted-foreground">{signal.caseIds.join(", ")}</p></li>)}</ul> : <p className="mt-3 text-sm text-muted-foreground">No active event clusters or interaction flags.</p>}{can(profile?.role, "safety:update") && <Button asChild variant="ghost" size="sm" className="mt-3 px-0"><Link to="/safety">Review signals<ArrowRight className="size-4" /></Link></Button>}</section>
      <section className="rounded-lg border border-border bg-surface p-5"><h2 className="mb-5 font-display text-base font-semibold">Recent actions</h2>{recentActions.length ? <Timeline items={recentActions} /> : <p className="text-sm text-muted-foreground">Workflow actions will appear here as the team progresses studies.</p>}</section></aside>
    </div>
  </PlatformPage>;
}

export const capabilities = [
  ["Research Portfolio Intelligence", "See study health in context and focus institutional attention where it matters.", FlaskConical],
  ["Ethics & CTRI Readiness", "Trace approvals, registrations and protocol alignment before activation.", BookOpenCheck],
  ["Participant Lifecycle Management", "Follow consent, visits, interventions and outcomes as one continuous journey.", TrendingUp],
  ["Pharmacovigilance & SAE Monitoring", "Investigate, escalate and close safety events against regulatory timelines.", ShieldCheck],
  ["Compliance & Audit Trail", "Maintain an inspection-ready chain of decisions, documents and accountability.", Check],
  ["Standards Export (FHIR & CDISC)", "Prepare validated exchange packages with clear evidence lineage.", ArrowRight],
  ["Explainable Risk Detection", "Understand why a study is at risk, who owns it and what action is required.", CircleAlert],
] as const;