import { Link } from "@tanstack/react-router";
import { ArrowRight, BookOpenCheck, Check, CircleAlert, FlaskConical, Leaf, ShieldCheck, TrendingUp } from "lucide-react";
import { toast } from "sonner";

import { AttentionItem, PlatformPage, ProgressBar, StatusPill, Timeline } from "@/components/trialshield";
import { Button } from "@/components/ui/button";
import { downloadClinicalReport } from "@/lib/clinical-report";

export function PortfolioWorkspace() {
  return <PlatformPage eyebrow="National research portfolio · 26 September 2026" title="Good morning, Dr. Kumar" description="Three matters require institutional attention. The rest of the portfolio is progressing within protocol." actions={<Button variant="secondary" onClick={() => { if (downloadClinicalReport("pdf")) toast.success("Print-ready weekly brief opened. Choose Save as PDF in the print dialog."); else toast.error("Allow pop-ups to open the weekly brief."); }}>Weekly brief<ArrowRight className="size-4" /></Button>}>
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1.5fr)_minmax(320px,.72fr)]">
      <div className="space-y-6">
        <section className="rounded-lg border border-border bg-surface p-5 shadow-xs sm:p-6">
          <div className="grid grid-cols-[minmax(0,1fr)_auto] items-start gap-5"><div><div className="flex items-center gap-2"><span className="size-2 rounded-full bg-risk" /><p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-risk">Institutional attention</p></div><h2 className="mt-2 font-display text-xl font-semibold">What needs action now</h2></div><StatusPill tone="risk">3 priorities</StatusPill></div>
          <div className="mt-2"><AttentionItem severity="critical" title="Expedited SAE notification due in 18 hours" meta="AIIA-OA-024 · Participant P-024-117" owner="Dr. Kavita Rao" action="Review" onAction={() => toast.info("SAE-2026-014 is queued for safety review.")} /><AttentionItem severity="critical" title="CTRI record differs from protocol v3.2" meta="Secondary outcome wording" owner="Regulatory Operations" action="Reconcile" onAction={() => toast.info("CTRI outcome mismatch assigned to Regulatory Operations.")} /><AttentionItem severity="warning" title="Recruitment at Site 04 is below threshold" meta="11% behind 30-day trajectory" owner="Site investigator" action="Examine" onAction={() => toast.info("Site 04 recruitment review opened.")} /></div>
        </section>
        <section className="grid gap-4 lg:grid-cols-2">
          <article className="rounded-lg border border-border bg-surface p-5"><div className="flex items-center justify-between"><div><p className="text-[11px] font-semibold uppercase tracking-[0.14em] text-secondary">Recruitment journey</p><h2 className="mt-1 font-display text-lg font-semibold">482 of 700 participants</h2></div><span className="font-display text-2xl font-semibold">69%</span></div><div className="mt-5"><ProgressBar value={69} /></div><div className="mt-5 grid grid-cols-3 divide-x divide-border text-center"><div><strong className="block text-sm">136</strong><span className="text-[11px] text-muted-foreground">Screening</span></div><div><strong className="block text-sm">482</strong><span className="text-[11px] text-muted-foreground">Enrolled</span></div><div><strong className="block text-sm">391</strong><span className="text-[11px] text-muted-foreground">Active</span></div></div></article>
          <article className="rounded-lg border border-border bg-surface p-5"><div className="flex items-center justify-between"><div><p className="text-[11px] font-semibold uppercase tracking-[0.14em] text-secondary">Portfolio health</p><h2 className="mt-1 font-display text-lg font-semibold">Controlled, with exceptions</h2></div><div className="grid size-14 place-items-center rounded-full border-4 border-secondary/20 font-display text-lg font-semibold text-primary">84</div></div><div className="mt-5 space-y-3 text-xs"><div className="flex justify-between"><span className="text-muted-foreground">Ethics readiness</span><strong>92%</strong></div><div className="flex justify-between"><span className="text-muted-foreground">Safety closure</span><strong>76%</strong></div><div className="flex justify-between"><span className="text-muted-foreground">Data completeness</span><strong>90%</strong></div></div></article>
        </section>
        <section className="rounded-lg border border-border bg-surface p-6"><div className="flex items-center justify-between"><div><p className="text-[11px] font-semibold uppercase tracking-[0.14em] text-secondary">Studies requiring attention</p><h2 className="mt-1 font-display text-xl font-semibold">Operational focus</h2></div><Button asChild variant="ghost" size="sm"><Link to="/studies">All studies<ArrowRight className="size-4" /></Link></Button></div><div className="mt-5 grid gap-4 md:grid-cols-3">{[
          ["AIIA-OA-024", "Knee osteoarthritis", "High", 68], ["AIIA-RA-019", "Rheumatoid arthritis", "Moderate", 81], ["AIIA-DM-031", "Nishamalaki outcomes", "Low", 46],
        ].map(([id, title, risk, progress]) => <Link key={id as string} to="/studies/$studyId" params={{ studyId: id as string }} className="rounded-md border border-border p-4 transition-colors hover:border-secondary/40 hover:bg-muted/40"><div className="flex justify-between gap-2"><span className="text-[10px] font-semibold text-secondary">{id}</span><StatusPill tone={risk === "High" ? "risk" : risk === "Moderate" ? "warn" : "good"}>{risk}</StatusPill></div><h3 className="mt-3 text-sm font-semibold">{title}</h3><div className="mt-5"><ProgressBar value={progress as number} tone={risk === "High" ? "risk" : "primary"} /></div><p className="mt-2 text-[11px] text-muted-foreground">{progress}% recruited</p></Link>)}</div></section>
      </div>
      <aside className="space-y-6"><section className="rounded-lg bg-primary p-6 text-primary-foreground"><div className="flex items-start justify-between"><div><p className="text-[11px] font-semibold uppercase tracking-[0.14em] text-primary-foreground/60">Safety monitoring</p><h2 className="mt-2 font-display text-xl font-semibold">Active surveillance</h2></div><ShieldCheck className="size-6 text-accent" /></div><p className="mt-5 text-4xl font-semibold">4</p><p className="mt-1 text-sm text-primary-foreground/65">open serious adverse events</p><div className="mt-6 border-t border-primary-foreground/15 pt-5"><div className="flex items-center justify-between text-sm"><span>Expedited reviews</span><strong>2</strong></div><div className="mt-3 flex items-center justify-between text-sm"><span>Follow-ups overdue</span><strong>1</strong></div></div><Button asChild variant="accent" className="mt-6 w-full"><Link to="/safety">Open safety workspace<ArrowRight className="size-4" /></Link></Button></section>
      <section className="rounded-lg border border-border bg-surface p-5"><h2 className="mb-5 font-display text-base font-semibold">Recent actions</h2><Timeline items={[{ title: "Protocol amendment logged", detail: "AIIA-OA-024 · v3.2", time: "14:32", state: "done" }, { title: "Medical review assigned", detail: "SAE-2026-014 · Dr. Rao", time: "12:18", state: "current" }, { title: "Site query resolved", detail: "Participant P-019-084", time: "09:45", state: "done" }]} /></section></aside>
    </div>
  </PlatformPage>;
}

export const capabilities = [
  ["Research Portfolio Intelligence", "See study health in context and focus institutional attention where it matters.", FlaskConical],
  ["Ethics & CTRI Readiness", "Trace approvals, registrations and protocol alignment before activation.", BookOpenCheck],
  ["Participant Lifecycle Management", "Follow consent, visits, interventions and outcomes as one continuous journey.", TrendingUp],
  ["Pharmacovigilance & SAE Monitoring", "Investigate, escalate and close safety events against regulatory timelines.", ShieldCheck],
  ["Compliance & Audit Trail", "Maintain an inspection-ready chain of decisions, documents and accountability.", Check],
  ["Standards Export (FHIR & CDISC)", "Prepare validated exchange packages with clear evidence lineage.", ArrowRight],
  ["Explainable Risk Detection", "Understand why a study is at risk, who owns it and what action is required.", CircleAlert],
] as const;