/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as ExportsRouteImport } from './routes/exports'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as StudiesRouteImport } from './routes/studies'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as StudiesStudyIdRouteImport } from './routes/studies.$studyId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportsRoute = ExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const StudiesRoute = StudiesRouteImport.update({
  id: '/studies',
  path: '/studies',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const StudiesStudyIdRoute = StudiesStudyIdRouteImport.update({
  id: '/$studyId',
  path: '/$studyId',
  getParentRoute: () => StudiesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/compliance': typeof ComplianceRoute
  '/documents': typeof DocumentsRoute
  '/exports': typeof ExportsRoute
  '/login': typeof LoginRoute
  '/platform': typeof PlatformRoute
  '/safety': typeof SafetyRoute
  '/studies': typeof StudiesRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/studies/$studyId': typeof StudiesStudyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/compliance': typeof ComplianceRoute
  '/documents': typeof DocumentsRoute
  '/exports': typeof ExportsRoute
  '/login': typeof LoginRoute
  '/platform': typeof PlatformRoute
  '/safety': typeof SafetyRoute
  '/studies': typeof StudiesRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/studies/$studyId': typeof StudiesStudyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/compliance': typeof ComplianceRoute
  '/documents': typeof DocumentsRoute
  '/exports': typeof ExportsRoute
  '/login': typeof LoginRoute
  '/platform': typeof PlatformRoute
  '/safety': typeof SafetyRoute
  '/studies': typeof StudiesRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/studies/$studyId': typeof StudiesStudyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analytics'
    | '/compliance'
    | '/documents'
    | '/exports'
    | '/login'
    | '/platform'
    | '/safety'
    | '/studies'
    | '/unauthorized'
    | '/studies/$studyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/analytics'
    | '/compliance'
    | '/documents'
    | '/exports'
    | '/login'
    | '/platform'
    | '/safety'
    | '/studies'
    | '/unauthorized'
    | '/studies/$studyId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analytics'
    | '/compliance'
    | '/documents'
    | '/exports'
    | '/login'
    | '/platform'
    | '/safety'
    | '/studies'
    | '/unauthorized'
    | '/studies/$studyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ComplianceRoute: typeof ComplianceRoute
  DocumentsRoute: typeof DocumentsRoute
  ExportsRoute: typeof ExportsRoute
  LoginRoute: typeof LoginRoute
  PlatformRoute: typeof PlatformRoute
  SafetyRoute: typeof SafetyRoute
  StudiesRoute: typeof StudiesRouteWithChildren
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exports': {
      id: '/exports'
      path: '/exports'
      fullPath: '/exports'
      preLoaderRoute: typeof ExportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studies': {
      id: '/studies'
      path: '/studies'
      fullPath: '/studies'
      preLoaderRoute: typeof StudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studies/$studyId': {
      id: '/studies/$studyId'
      path: '/$studyId'
      fullPath: '/studies/$studyId'
      preLoaderRoute: typeof StudiesStudyIdRouteImport
      parentRoute: typeof StudiesRoute
    }
  }
}

interface StudiesRouteChildren {
  StudiesStudyIdRoute: typeof StudiesStudyIdRoute
}

const StudiesRouteChildren: StudiesRouteChildren = {
  StudiesStudyIdRoute: StudiesStudyIdRoute,
}

const StudiesRouteWithChildren =
  StudiesRoute._addFileChildren(StudiesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnalyticsRoute: AnalyticsRoute,
  ComplianceRoute: ComplianceRoute,
  DocumentsRoute: DocumentsRoute,
  ExportsRoute: ExportsRoute,
  LoginRoute: LoginRoute,
  PlatformRoute: PlatformRoute,
  SafetyRoute: SafetyRoute,
  StudiesRoute: StudiesRouteWithChildren,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
