77create table if not exists public.compliance_items (
  id text primary key,
  study_id text not null,
  title text not null,
  detail text not null,
  owner text not null,
  severity text not null check (severity in ('High', 'Medium')),
  resolved boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.audit_events
  add column if not exists event_order bigint generated by default as identity;

create unique index if not exists audit_events_event_order_uidx
  on public.audit_events (event_order);

alter table public.documents
  add column if not exists record_key text;

update public.documents
set record_key = id::text
where record_key is null;

create unique index if not exists documents_record_key_uidx
  on public.documents (record_key);

alter table public.compliance_items enable row level security;

drop policy if exists compliance_items_study_read on public.compliance_items;
create policy compliance_items_study_read
on public.compliance_items for select to authenticated
using (public.can_access_study(study_id));

drop policy if exists compliance_items_study_insert on public.compliance_items;
create policy compliance_items_study_insert
on public.compliance_items for insert to authenticated
with check (
  public.can_access_study(study_id)
  and public.get_my_role() in ('ADMIN', 'COMPLIANCE_OFFICER')
);

drop policy if exists compliance_items_study_update on public.compliance_items;
create policy compliance_items_study_update
on public.compliance_items for update to authenticated
using (
  public.can_access_study(study_id)
  and public.get_my_role() in ('ADMIN', 'COMPLIANCE_OFFICER')
)
with check (
  public.can_access_study(study_id)
  and public.get_my_role() in ('ADMIN', 'COMPLIANCE_OFFICER')
);

revoke all on public.compliance_items from anon;
grant select, insert, update on public.compliance_items to authenticated;