alter table public.studies
  add column if not exists rule_pack text not null default 'academic-asu';

create table if not exists public.safety_cases (
  id text primary key,
  study_id text not null,
  title text not null,
  severity text not null check (severity in ('AE', 'SAE')),
  stage text not null check (stage in ('reported', 'medical-review', 'regulatory-reporting', 'follow-up', 'ready-to-close', 'signal-review', 'closed')),
  owner text not null,
  onset_at timestamptz,
  aware_at timestamptz,
  reported_at timestamptz,
  batch_id text,
  causality text,
  prakriti text,
  concomitant_meds text[] not null default '{}',
  interaction_suspected boolean not null default false,
  meddra_term text,
  namaste_code text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.compliance_items (
  id text primary key,
  study_id text not null,
  title text not null,
  detail text not null,
  owner text not null,
  severity text not null check (severity in ('High', 'Medium')),
  resolved boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.documents
  add column if not exists record_key text;

alter table public.audit_events
  add column if not exists event_order bigint generated by default as identity;

create unique index if not exists audit_events_event_order_uidx
  on public.audit_events (event_order);

update public.documents
set record_key = id::text
where record_key is null;

create unique index if not exists documents_record_key_uidx
  on public.documents (record_key);

alter table public.safety_cases enable row level security;
alter table public.compliance_items enable row level security;

drop policy if exists documents_authenticated_read on public.documents;
drop policy if exists documents_study_read on public.documents;
create policy documents_study_read
on public.documents for select to authenticated
using (public.can_access_study(study_id));

drop policy if exists documents_study_insert on public.documents;
create policy documents_study_insert
on public.documents for insert to authenticated
with check (
  public.can_access_study(study_id)
  and public.get_my_role() in ('ADMIN', 'PI', 'COMPLIANCE_OFFICER')
);

drop policy if exists documents_study_update on public.documents;
create policy documents_study_update
on public.documents for update to authenticated
using (
  public.can_access_study(study_id)
  and public.get_my_role() in ('ADMIN', 'PI', 'COMPLIANCE_OFFICER')
)
with check (
  public.can_access_study(study_id)
  and public.get_my_role() in ('ADMIN', 'PI', 'COMPLIANCE_OFFICER')
);

drop policy if exists safety_cases_study_read on public.safety_cases;
create policy safety_cases_study_read
on public.safety_cases for select to authenticated
using (public.can_access_study(study_id));

drop policy if exists safety_cases_study_insert on public.safety_cases;
create policy safety_cases_study_insert
on public.safety_cases for insert to authenticated
with check (
  public.can_access_study(study_id)
  and public.get_my_role() in ('ADMIN', 'SAFETY_OFFICER')
);

drop policy if exists safety_cases_study_update on public.safety_cases;
create policy safety_cases_study_update
on public.safety_cases for update to authenticated
using (
  public.can_access_study(study_id)
  and public.get_my_role() in ('ADMIN', 'SAFETY_OFFICER')
)
with check (
  public.can_access_study(study_id)
  and public.get_my_role() in ('ADMIN', 'SAFETY_OFFICER')
);

drop policy if exists compliance_items_study_read on public.compliance_items;
create policy compliance_items_study_read
on public.compliance_items for select to authenticated
using (public.can_access_study(study_id));

drop policy if exists compliance_items_study_insert on public.compliance_items;
create policy compliance_items_study_insert
on public.compliance_items for insert to authenticated
with check (
  public.can_access_study(study_id)
  and public.get_my_role() in ('ADMIN', 'COMPLIANCE_OFFICER')
);

drop policy if exists compliance_items_study_update on public.compliance_items;
create policy compliance_items_study_update
on public.compliance_items for update to authenticated
using (
  public.can_access_study(study_id)
  and public.get_my_role() in ('ADMIN', 'COMPLIANCE_OFFICER')
)
with check (
  public.can_access_study(study_id)
  and public.get_my_role() in ('ADMIN', 'COMPLIANCE_OFFICER')
);

drop policy if exists audit_events_authenticated_read on public.audit_events;
drop policy if exists audit_events_study_read on public.audit_events;
create policy audit_events_study_read
on public.audit_events for select to authenticated
using (
  (study_id is not null and public.can_access_study(study_id))
  or (study_id is null and public.has_role('ADMIN'))
);

drop policy if exists audit_events_authenticated_insert on public.audit_events;
drop policy if exists audit_events_study_insert on public.audit_events;
create policy audit_events_study_insert
on public.audit_events for insert to authenticated
with check (
  user_id = (select auth.uid())
  and (
    (study_id is not null and public.can_access_study(study_id))
    or (study_id is null and public.has_role('ADMIN'))
  )
);

revoke all on public.safety_cases, public.compliance_items, public.documents, public.audit_events from anon;
grant select, insert, update on public.safety_cases, public.compliance_items, public.documents to authenticated;
grant select, insert on public.audit_events to authenticated;

create or replace function public.add_study_creator_as_member()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if (select auth.uid()) is not null then
    insert into public.study_members (study_id, user_id, role)
    values (new.study_code, (select auth.uid()), public.get_my_role())
    on conflict (study_id, user_id) do nothing;
  end if;
  return new;
end;
$$;

drop trigger if exists studies_add_creator_as_member on public.studies;
create trigger studies_add_creator_as_member
after insert on public.studies
for each row execute function public.add_study_creator_as_member();

create or replace function public.persist_study_workflow(
  p_study_code text,
  p_operation text,
  p_amount integer default null,
  p_expected_stage text default null,
  p_next_stage text default null
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_study public.studies%rowtype;
  v_role public.app_role;
  v_expected_next text;
begin
  if not public.can_access_study(p_study_code) then
    raise exception 'Study access denied';
  end if;

  v_role := public.get_my_role();
  select * into v_study
  from public.studies
  where study_code = p_study_code
  for update;

  if not found then
    raise exception 'Study not found';
  end if;

  if p_operation = 'advance' then
    if v_role not in ('ADMIN', 'PI') then
      raise exception 'Study update permission denied';
    end if;
    if v_study.stage is distinct from p_expected_stage then
      raise exception 'Study stage changed; refresh and retry';
    end if;

    v_expected_next := case v_study.stage
      when 'protocol' then 'ethics'
      when 'ethics' then 'ctri'
      when 'ctri' then 'sites'
      when 'sites' then 'recruitment'
      when 'recruitment' then 'follow-up'
      when 'follow-up' then 'close-out'
      when 'close-out' then 'closed'
      else null
    end;
    if v_expected_next is null or v_expected_next is distinct from p_next_stage then
      raise exception 'Invalid study stage transition';
    end if;
    if v_study.stage = 'recruitment' and v_study.enrolled_participants < v_study.target_participants then
      raise exception 'Recruitment target has not been reached';
    end if;
    if v_study.stage = 'follow-up' and v_study.visits_complete < v_study.enrolled_participants then
      raise exception 'Follow-up visits are incomplete';
    end if;
    if v_study.stage = 'close-out' and exists (
      select 1 from public.safety_cases
      where study_id = p_study_code and severity = 'SAE' and stage <> 'closed'
    ) then
      raise exception 'Open serious safety cases remain';
    end if;

    update public.studies
    set stage = p_next_stage,
        status = case p_next_stage
          when 'protocol' then 'Protocol'
          when 'ethics' then 'Ethics'
          when 'ctri' then 'CTRI'
          when 'sites' then 'Sites'
          when 'recruitment' then 'Recruitment'
          when 'follow-up' then 'Follow-up'
          when 'close-out' then 'Close-out'
          when 'closed' then 'Closed'
        end,
        activated_sites = case when p_next_stage = 'recruitment' then greatest(activated_sites, 1) else activated_sites end,
        archived = (p_next_stage = 'closed')
    where study_code = p_study_code;
    return 0;
  elsif p_operation in ('enrollment', 'visits') then
    if v_role not in ('ADMIN', 'PI', 'CRC') then
      raise exception 'Study progress update permission denied';
    end if;
    if p_amount is null or p_amount < 1 then
      raise exception 'Amount must be positive';
    end if;

    if p_operation = 'enrollment' then
      if v_study.stage <> 'recruitment' or p_amount > v_study.target_participants - v_study.enrolled_participants then
        raise exception 'Enrollment is not available for this study state';
      end if;
      update public.studies
      set enrolled_participants = enrolled_participants + p_amount
      where study_code = p_study_code;
    else
      if v_study.stage <> 'follow-up' or p_amount > v_study.enrolled_participants - v_study.visits_complete then
        raise exception 'Visits are not available for this study state';
      end if;
      update public.studies
      set visits_complete = visits_complete + p_amount
      where study_code = p_study_code;
    end if;
    return p_amount;
  end if;

  raise exception 'Unsupported workflow operation';
end;
$$;

revoke all on function public.persist_study_workflow(text, text, integer, text, text) from public;
grant execute on function public.persist_study_workflow(text, text, integer, text, text) to authenticated;